# 标定板参数 (确认和你用的一致)
pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40.0

# 重投影误差: 0.1359px
camera_matrix: [27825.424980511278, 0, 634.6534891244487, 0, 45358.355227356515, 590.92437365207991, 0, 0, 1]
distort_coeffs: [8.8764311865366743, -13079.497395844041, -0.017182410338214136, 0.57624533454500948, 0]

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]