enemy_color: "red"
#enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov8
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/best.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 3
gain: 16.0
vid_pid: "2bdf:0001"

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"



#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
serial_baudrate: 460800

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 75
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 1.7 # degree -2.5
pitch_offset: -1  # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 2  # rad/s
high_speed_delay_time: 0.02 # s
low_speed_delay_time: 0.05 # s

#####-----shooter参数-----#####
first_tolerance: 2 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# # 重投影误差: 0.1833px
# camera_matrix: [2414.9359264386621, 0, 717.26243105567414, 0, 2418.0489262208148, 582.68540529942845, 0, 0, 1]
# distort_coeffs: [-0.0209453389287673, 0.15028138841073832, -0.0006517722113234505, -0.0016861906197686788, 0]

# # 相机同理想情况的偏角: yaw-1.11 pitch0.01 roll-0.06 degree
# # 标定板到世界坐标系原点的水平距离: 1.20 m
# # 标定板同竖直摆放时的偏角: yaw123.89 pitch14.05 roll-0.86 degree
# R_camera2gimbal: [0.01928451708725664, 0.00012696140743255463, 0.99981402834802846, -0.99981344688553653, -0.0010834913551969569, 0.019284643459122196, 0.0010857382619952124, -0.99999940496346484, 0.00010604311483339372]
# t_camera2gimbal: [0.13089617453251859, 0.0038468007459533785, 0.094139945222010288]

#  hero重投影误差: 0.0416px
camera_matrix: [1462.8709543122836, 0, 714.42907334451832, 0, 1462.4766427972997, 541.7059967226121, 0, 0, 1]
distort_coeffs: [-0.1211477883773746, 0.15824655435601387, 0.00012652706825206381, 0.00051299525279652626, 0]


# 相机同理想情况的偏角: yaw0.93 pitch-2.10 roll0.75 degree
# 标定板到世界坐标系原点的水平距离: 2.56 m
# 标定板同竖直摆放时的偏角: yaw-27.77 pitch1.95 roll0.58 degree
R_camera2gimbal: [-0.016711260438829624, -0.036507040888000532, 0.99919365977779673, -0.99977443457271675, 0.013710975127896825, -0.016220022683314444, -0.013107774385861925, -0.99923933325637448, -0.03672793383795641]
t_camera2gimbal: [0.18177877835008543, 0.052837043573663936, 0.16332135392188338]
#####-----MPC Planner 参数-----#####
# 允许的最大角加速度 (rad/s^2)
max_yaw_acc: 200.0
max_pitch_acc: 100.0

# 状态权重矩阵 Q [pos_weight, vel_weight]
# 越大越强行跟踪目标
Q_yaw: [2000.0, 10.0]
Q_pitch: [2000.0, 10.0]

# 控制权重矩阵 R [acc_weight]
# 越小响应越快，但也越容易震荡
R_yaw: [0.01]
R_pitch: [0.01]

# 允许开火的追踪误差阈值 (rad)
fire_thresh: 0.02

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.520   # s
predict_time: 0.100     # s