pattern_cols: 9
pattern_rows: 7
center_distance_mm: 20

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 16.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"


#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
serial_baudrate: 460800


# #10.7
# #重投影误差: 0.3074px
# camera_matrix: [2327.4739232956272, 0, 697.24202757922922, 0, 2326.0604281821647, 561.32283810282172, 0, 0, 1]
# distort_coeffs: [-0.063530482426696747, 0.12980032278204473, -0.00073457675924140067, -0.0023769793696679737, 0]

# # 相机同理想情况的偏角: yaw-26.56 pitch69.80 roll97.13 degree
# R_camera2gimbal: [0.77756071741657828, -0.54772013162234379, 0.30887212264336567, 0.5272551788291695, 0.83556533538251776, 0.15437793464391586, -0.34263874142956519, 0.04281620864466007, 0.93849105757532947]
# t_camera2gimbal: [-0.17398834356974807, -0.18552729523548242, 0.15990022202681645]


# # 相机同理想情况的偏角: yaw83.13 pitch-38.74 roll-152.56 degree
# # 标定板到世界坐标系原点的水平距离: 0.01 m
# # 标定板同竖直摆放时的偏角: yaw96.16 pitch17.71 roll-138.30 degree
# R_camera2gimbal: [0.91554932544449108, -0.39121374473957016, 0.093387572004954594, -0.1801799872274113, -0.60652523568629724, -0.77437866104278097, 0.35958949495343767, 0.69215528922527381, -0.62579265792801531]
# t_camera2gimbal: [-0.14260391863420782, 0.78986324063887625, 0.64479565223153346]

# #10.8
# # 重投影误差: 0.0702px
# camera_matrix: [2336.3136996660851, 0, 694.85566287168956, 0, 2336.7953075420587, 581.6680177720516, 0, 0, 1]
# distort_coeffs: [-0.063486354673188208, 0.073172977184996893, 0.00040721475783536682, -0.0020790587281971076, 0]

# # # 相机同理想情况的偏角: yaw-1.17 pitch0.40 roll-0.10 degree
# # R_camera2gimbal: [0.020439200198691498, 0.0070044519458882376, 0.99976656112723405, -0.99978968944744329, -0.001535199495128925, 0.020450428775335778, 0.0016780851655188479, -0.99997429007722383, 0.0069716005859032926]
# # t_camera2gimbal: [0.115113638394087, 0.0078378987140867926, -0.044029756330290694]

# # 相机同理想情况的偏角: yaw-0.38 pitch0.61 roll0.01 degree
# # 标定板到世界坐标系原点的水平距离: 1.71 m
# # 标定板同竖直摆放时的偏角: yaw-0.06 pitch0.72 roll0.01 degree
# R_camera2gimbal: [0.006579760150768648, 0.010629532665952755, 0.99992185684265444, -0.99997834025994148, 0.00023045775210685251, 0.0065776819775071891, -0.00016052205796427251, -0.99994347836491637, 0.010630818789771892]
# t_camera2gimbal: [0.10706889780243246, 0.005538290559483035, -0.040263048818448381]


# #10.16
# 重投影误差: 0.0447px
#camera_matrix: [2340.661567127544, 0, 700.06489037588619, 0, 2340.9437532322354, 566.6079025555232, 0, 0, 1]
#distort_coeffs: [-0.05808452117809166, 0.07788935143363003, 0.00061634394527499965, -0.0007302501646552109, 0]

# # 相机同理想情况的偏角: yaw0.89 pitch0.08 roll178.41 degree
# # 标定板到世界坐标系原点的水平距离: 2.08 m
# # 标定板同竖直摆放时的偏角: yaw19.07 pitch-1.84 roll179.03 degree
# R_camera2gimbal: [0.015603708152345772, -0.0010183461327402821, 0.99987773615730158, 0.99948811317966635, 0.027948394748152038, -0.015569163225809798, -0.027929122872852152, 0.99960884860136923, 0.0014539234497531535]
# t_camera2gimbal: [0.13736444867265249, -0.0024387862390420553, 0.057903139402793957]

#10.162

# 相机同理想情况的偏角: yaw-0.89 pitch-0.08 roll-1.60 degree
# 标定板到世界坐标系原点的水平距离: 2.08 m
# 标定板同竖直摆放时的偏角: yaw-19.07 pitch1.84 roll-0.98 degree
#R_camera2gimbal: [0.015603708152345772, -0.0010183461327402821, 0.99987773615730158, -0.99948811317966635, -0.027948394748152038, 0.015569163225809798, 0.027929122872852152, -0.99960884860136923, -0.0014539234497531535]
#t_camera2gimbal: [0.13736444867265249, 0.0024387862390420553, -0.057903139402793957]


#11.14

# 重投影误差: 0.0461px
#camera_matrix: [2365.1516720418413, 0, 705.78429815243578, 0, 2363.6692749983722, 554.95234073458982, 0, 0, 1]
#distort_coeffs: [-0.058375717619746914, 0.064527069082293206, -0.00019641891394758169, -0.00068966403508933074, 0]

#111
# 相机同理想情况的偏角: yaw1.46 pitch0.38 roll178.27 degree
# 标定板到世界坐标系原点的水平距离: 1.98 m
# 标定板同竖直摆放时的偏角: yaw-165.56 pitch7.69 roll-0.60 degree
#R_camera2gimbal: [0.02569981265411073, -0.0057665963950229646, 0.99965307281854565, 0.99920686306286832, 0.030574240142040365, -0.025511970676513836, -0.030416515868949667, 0.99951586390899949, 0.0065477749381127786]
#t_camera2gimbal: [0.12402836657619365, 0.0014985707884802764, 0.056602272683762694]
#1-1-1
# 相机同理想情况的偏角: yaw-1.46 pitch-0.38 roll-1.74 degree
# 标定板到世界坐标系原点的水平距离: 1.98 m
# 标定板同竖直摆放时的偏角: yaw165.56 pitch-7.69 roll179.41 degree
#R_camera2gimbal: [0.02569981265411073, -0.0057665963950229646, 0.99965307281854565, -0.99920686306286832, -0.030574240142040365, 0.025511970676513836, 0.030416515868949667, -0.99951586390899949, -0.0065477749381127786]
#t_camera2gimbal: [0.12402836657619365, -0.0014985707884802764, -0.056602272683762694]

#-----

# 重投影误差: 0.0603px
#camera_matrix: [2318.6413406198758, 0, 706.00988840107982, 0, 2319.0841782597381, 576.70272260508466, 0, 0, 1]
#distort_coeffs: [-0.062548620636062979, 0.078086423617440809, 0.00065637201752308586, -0.00051893002090232232, 0]
# 相机同理想情况的偏角: yaw-0.46 pitch-0.95 roll0.78 degree
# 标定板到世界坐标系原点的水平距离: 2.22 m
# 标定板同竖直摆放时的偏角: yaw34.85 pitch5.17 roll0.45 degree
#R_camera2gimbal: [0.0078408519555110585, -0.016666310858230417, 0.99983036317316742, -0.99987702738297002, 0.013449140431189924, 0.0080654034900839115, -0.013581279483446389, -0.99977065105154928, -0.016558808639318107]
#t_camera2gimbal: [0.17895111220511642, 0.0081211501404892337, -0.06908363097344733]


#  hero重投影误差: 0.0416px
camera_matrix: [1462.8709543122836, 0, 714.42907334451832, 0, 1462.4766427972997, 541.7059967226121, 0, 0, 1]
distort_coeffs: [-0.1211477883773746, 0.15824655435601387, 0.00012652706825206381, 0.00051299525279652626, 0]


# 相机同理想情况的偏角: yaw0.93 pitch-2.10 roll0.75 degree
# 标定板到世界坐标系原点的水平距离: 2.56 m
# 标定板同竖直摆放时的偏角: yaw-27.77 pitch1.95 roll0.58 degree
R_camera2gimbal: [-0.016711260438829624, -0.036507040888000532, 0.99919365977779673, -0.99977443457271675, 0.013710975127896825, -0.016220022683314444, -0.013107774385861925, -0.99923933325637448, -0.03672793383795641]
t_camera2gimbal: [0.18177877835008543, 0.052837043573663936, 0.16332135392188338]
